# Generated by Django 4.0.6 on 2022-08-31 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_email_alter_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
