# Generated by Django 4.0.6 on 2022-09-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='date_employed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
