# Generated by Django 4.0.6 on 2022-08-29 08:58

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enquiry_no', models.PositiveIntegerField(blank=True)),
                ('surn_name', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('contact_no', models.CharField(blank=True, max_length=14)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('guardians_name', models.CharField(blank=True, max_length=200)),
                ('guardians_contact_no', models.CharField(blank=True, max_length=14)),
                ('educational_qualifications', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('High School', 'High School'), ('Undergraduate', 'Undergraduate'), ('Graduate', 'Graduate'), ('Vocational School', 'Vocational School')], max_length=52)),
                ('eductional_others', models.CharField(blank=True, max_length=200)),
                ('how_you_heard', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Seminar', 'Seminar'), ('Newspapers', 'Newspapers'), ('Billboard', 'Billboard'), ('Internet', 'Internet'), ('Friends/Relatives', 'Friends/Relatives'), ('Fliers/Handbills', 'Fliers/Handbills')], max_length=72)),
                ('how_you_heard_others', models.CharField(blank=True, max_length=200)),
                ('course_of_interest', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Software Programming', 'Software Programming'), ('System Engineer', 'System Engineer'), ('Hardware/Networking', 'Hardware/Networking')], max_length=56)),
                ('course_of_interest_others', models.CharField(blank=True, max_length=200)),
                ('counselor', models.CharField(blank=True, max_length=200)),
                ('remark', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
            },
        ),
    ]
