# Generated by Django 4.0.6 on 2022-09-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquires',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquires',
            name='enquiry_no',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
