# Generated by Django 4.0.6 on 2022-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='is_completed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
